### ISSUE TITLE
Implement RotationGestureRecognizer

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/family-direct-manipulation-android#10]
Spec: https://material-motion.github.io/material-motion/starmap/specifications/primitives/gesture_recognizers/RotationGestureRecognizer

**Comment by pingpongboss** [comment]
💻 I'm working on a diff at http://codereview.cc/D1966

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1966
