### ISSUE TITLE
Support velocity for Drag, Scale, Rotate gesture recognizers.

### ISSUE THREAD

**Issue by pingpongboss** [material-motion-archive/family-direct-manipulation-android#15]
Drag needs to track the movement of the centroid (ignoring any jumps mid-gesture due to adding/removing fingers) over time.

Scale needs to track the change in span (average distance from centroid times 2) over time.

Rotate needs to track the angle of rotation over time.

Currently, drag track velocity, but it is most likely straight up wrong.

**Comment by pingpongboss** [comment]
@jverkoey Does this belong in 1.0.0? I think so.

**Comment by jverkoey** [comment]
Seems reasonable.

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D2007
