### ISSUE TITLE
Implement Rotatable plan

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/family-direct-manipulation-android#3]
Spec: https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/motion_family/direct_manipulation.html

**Comment by pingpongboss** [comment]
💻 I'm working on a diff at http://codereview.cc/D1966

**Comment by pingpongboss** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1966
